import streamlit as st

# 118개 원소와 다양한 쓰임새 정보
elements_info = {
    "H":  {"number": 1,   "name": "수소",        "usage": "연료 전지, 로켓 연료, 암모니아 합성"},
    "He": {"number": 2,   "name": "헬륨",        "usage": "MRI 냉각제, 풍선, 레이저"},
    "Li": {"number": 3,   "name": "리튬",        "usage": "리튬 이온 배터리, 항우울제"},
    "Be": {"number": 4,   "name": "베릴륨",      "usage": "항공 우주 부품, X선 창문"},
    "B":  {"number": 5,   "name": "붕소",        "usage": "세라믹, 살충제, 강화유리"},
    "C":  {"number": 6,   "name": "탄소",        "usage": "생명체, 연료, 그래핀, 다이아몬드"},
    "N":  {"number": 7,   "name": "질소",        "usage": "비료, 냉매, 질소 고정"},
    "O":  {"number": 8,   "name": "산소",        "usage": "호흡, 연소 촉진제, 의료용"},
    "F":  {"number": 9,   "name": "플루오린",    "usage": "치약, 냉매, 테플론 제조"},
    "Ne": {"number": 10,  "name": "네온",        "usage": "네온사인, 레이저, 조명"},
    "Na": {"number": 11,  "name": "나트륨",      "usage": "염, 비누, 화학 반응 촉매"},
    "Mg": {"number": 12,  "name": "마그네슘",    "usage": "경량 합금, 의학, 조명 폭죽"},
    "Al": {"number": 13,  "name": "알루미늄",    "usage": "포장재, 항공기 부품, 전기선"},
    "Si": {"number": 14,  "name": "규소",        "usage": "반도체, 태양광, 유리"},
    "P":  {"number": 15,  "name": "인",          "usage": "비료, 성냥, 세제"},
    "S":  {"number": 16,  "name": "황",          "usage": "고무 가황, 화학 산업, 화약"},
    "Cl": {"number": 17,  "name": "염소",        "usage": "소독제, 플라스틱 제조, 수영장"},
    "Ar": {"number": 18,  "name": "아르곤",      "usage": "용접 보호가스, 조명, 보존"},
    "K":  {"number": 19,  "name": "칼륨",        "usage": "비료, 비누, 식품 첨가물"},
    "Ca": {"number": 20,  "name": "칼슘",        "usage": "시멘트, 뼈 건강, 제초제"},
    "Sc": {"number": 21,  "name": "스칸듐",      "usage": "항공기 합금, 조명"},
    "Ti": {"number": 22,  "name": "티타늄",      "usage": "항공 우주, 의료 임플란트, 골프 클럽"},
    "V":  {"number": 23,  "name": "바나듐",      "usage": "강철 합금, 촉매"},
    "Cr": {"number": 24,  "name": "크롬",        "usage": "스테인리스강, 도금"},
    "Mn": {"number": 25,  "name": "망간",        "usage": "강화 합금, 배터리, 비료"},
    "Fe": {"number": 26,  "name": "철",          "usage": "건축, 자동차, 기계"},
    "Co": {"number": 27,  "name": "코발트",      "usage": "자석, 배터리, 염료"},
    "Ni": {"number": 28,  "name": "니켈",        "usage": "도금, 배터리, 합금"},
    "Cu": {"number": 29,  "name": "구리",        "usage": "전선, 배관, 동전"},
    "Zn": {"number": 30,  "name": "아연",        "usage": "도금, 배터리, 화장품"},
    "Ga": {"number": 31,  "name": "갈륨",        "usage": "반도체, LED"},
    "Ge": {"number": 32,  "name": "저마늄",      "usage": "반도체, 적외선 광학"},
    "As": {"number": 33,  "name": "비소",        "usage": "살충제, 반도체"},
    "Se": {"number": 34,  "name": "셀레늄",      "usage": "전자제품, 유리 착색"},
    "Br": {"number": 35,  "name": "브롬",        "usage": "소독제, 난연제"},
    "Kr": {"number": 36,  "name": "크립톤",      "usage": "조명, 레이저"},
    "Rb": {"number": 37,  "name": "루비듐",      "usage": "연구용, 원자시계"},
    "Sr": {"number": 38,  "name": "스트론튬",    "usage": "조명, 자기 재료"},
    "Y":  {"number": 39,  "name": "이트륨",      "usage": "초전도체, 조명"},
    "Zr": {"number": 40,  "name": "지르코늄",    "usage": "원자력, 의료 기기"},
    "Nb": {"number": 41,  "name": "나이오븀",    "usage": "초전도체, 강철 합금"},
    "Mo": {"number": 42,  "name": "몰리브덴",    "usage": "강화 합금, 촉매"},
    "Tc": {"number": 43,  "name": "테크네튬",    "usage": "의학 영상, 방사성 추적자"},
    "Ru": {"number": 44,  "name": "루테늄",      "usage": "촉매, 전자제품"},
    "Rh": {"number": 45,  "name": "로듐",        "usage": "촉매, 도금"},
    "Pd": {"number": 46,  "name": "팔라듐",      "usage": "촉매, 전자제품"},
    "Ag": {"number": 47,  "name": "은",          "usage": "장신구, 전자제품, 사진술"},
    "Cd": {"number": 48,  "name": "카드뮴",      "usage": "배터리, 안료"},
    "In": {"number": 49,  "name": "인듐",        "usage": "전자제품, 반도체"},
    "Sn": {"number": 50,  "name": "주석",        "usage": "도금, 납땜"},
    "Sb": {"number": 51,  "name": "안티몬",      "usage": "합금, 반도체"},
    "Te": {"number": 52,  "name": "텔루륨",      "usage": "반도체, 합금"},
    "I":  {"number": 53,  "name": "아이오딘",    "usage": "소독제, 조영제"},
    "Xe": {"number": 54,  "name": "크세논",      "usage": "조명, 마취제"},
    "Cs": {"number": 55,  "name": "세슘",        "usage": "원자시계, 광전자"},
    "Ba": {"number": 56,  "name": "바륨",        "usage": "X선 조영제, 합금"},
    "La": {"number": 57,  "name": "란타넘",      "usage": "광학 렌즈, 촉매"},
    "Ce": {"number": 58,  "name": "세륨",        "usage": "촉매, 광택제"},
    "Pr": {"number": 59,  "name": "프라세오디뮴","usage": "자석, 조명"},
    "Nd": {"number": 60,  "name": "네오디뮴",    "usage": "강력 자석, 레이저"},
    "Pm": {"number": 61,  "name": "프로메튬",    "usage": "방사성 연구"},
    "Sm": {"number": 62,  "name": "사마륨",      "usage": "자석, 레이저"},
    "Eu": {"number": 63,  "name": "유로퓸",      "usage": "형광등, 핵연료"},
    "Gd": {"number": 64,  "name": "가돌리늄",    "usage": "MRI 대비제, 형광체"},
    "Tb": {"number": 65,  "name": "터븀",        "usage": "형광체, 자석"},
    "Dy": {"number": 66,  "name": "디스프로슘",  "usage": "자석, 레이저"},
    "Ho": {"number": 67,  "name": "홀뮴",        "usage": "레이저, 자기"},
    "Er": {"number": 68,  "name": "어븀",        "usage": "광섬유 증폭기, 레이저"},
    "Tm": {"number": 69,  "name": "툴륨",        "usage": "레이저, 방사선원"},
    "Yb": {"number": 70,  "name": "이터븀",      "usage": "합금, 레이저"},
    "Lu": {"number": 71,  "name": "루테튬",      "usage": "의학, 촉매"},
    "Hf": {"number": 72,  "name": "하프늄",      "usage": "원자력, 반도체"},
    "Ta": {"number": 73,  "name": "탄탈럼",      "usage": "전자제품, 수술용 기구"},
    "W":  {"number": 74,  "name": "텅스텐",      "usage": "전구 필라멘트, 합금"},
    "Re": {"number": 75,  "name": "레늄",        "usage": "촉매, 고온 합금"},
    "Os": {"number": 76,  "name": "오스뮴",      "usage": "합금, 촉매"},
    "Ir": {"number": 77,  "name": "이리듐",      "usage": "촉매, 전기 접점"},
    "Pt": {"number": 78,  "name": "백금",        "usage": "촉매, 장신구"},
    "Au": {"number": 79,  "name": "금",          "usage": "장신구, 전자제품, 투자"},
    "Hg": {"number": 80,  "name": "수은",        "usage": "온도계, 조명, 배터리"},
    "Tl": {"number": 81,  "name": "탈륨",        "usage": "전자제품, 독성 연구"},
    "Pb": {"number": 82,  "name": "납",          "usage": "배터리, 방사선 차단"},
    "Bi": {"number": 83,  "name": "비스무트",    "usage": "화장품, 약품, 합금"},
    "Po": {"number": 84,  "name": "폴로늄",      "usage": "방사성 열원"},
    "At": {"number": 85,  "name": "아스타틴",    "usage": "방사성 연구"},
    "Rn": {"number": 86,  "name": "라돈",        "usage": "방사성 가스, 지하 탐사"},
    "Fr": {"number": 87,  "name": "프랑슘",      "usage": "방사성 연구"},
    "Ra": {"number": 88,  "name": "라듐",        "usage": "방사선 치료"},
    "Ac": {"number": 89,  "name": "악티늄",      "usage": "방사성 연구"},
    "Th": {"number": 90,  "name": "토륨",        "usage": "원자력, 고성능 세라믹"},
    "Pa": {"number": 91,  "name": "프로트악티늄","usage": "방사성 연구"},
    "U":  {"number": 92,  "name": "우라늄",      "usage": "원자력 연료, 무기"},
    "Np": {"number": 93,  "name": "넵투늄",      "usage": "핵연료, 방사성 연구"},
    "Pu": {"number": 94,  "name": "플루토늄",    "usage": "핵무기, 원자력"},
    "Am": {"number": 95,  "name": "아메리슘",    "usage": "연기 감지기, 방사성 연구"},
    "Cm": {"number": 96,  "name": "퀴륨",        "usage": "방사성 연구"},
    "Bk": {"number": 97,  "name": "버클륨",      "usage": "방사성 연구"},
    "Cf": {"number": 98,  "name": "캘리포늄",    "usage": "중성자원, 방사성 연구"},
    "Es": {"number": 99,  "name": "아인슈타이늄","usage": "방사성 연구"},
    "Fm": {"number": 100, "name": "페르뮴",      "usage": "방사성 연구"},
    "Md": {"number": 101, "name": "멘델레븀",    "usage": "방사성 연구"},
    "No": {"number": 102, "name": "노벨륨",      "usage": "방사성 연구"},
    "Lr": {"number": 103, "name": "로렌슘",      "usage": "방사성 연구"},
    "Rf": {"number": 104, "name": "러더포듐",    "usage": "합성 원소"},
    "Db": {"number": 105, "name": "더브늄",      "usage": "합성 원소"},
    "Sg": {"number": 106, "name": "시보귬",      "usage": "합성 원소"},
    "Bh": {"number": 107, "name": "보륨",        "usage": "합성 원소"},
    "Hs": {"number": 108, "name": "하슘",        "usage": "합성 원소"},
    "Mt": {"number": 109, "name": "마이트너륨",  "usage": "합성 원소"},
    "Ds": {"number": 110, "name": "다름슈타튬",  "usage": "합성 원소"},
    "Rg": {"number": 111, "name": "렌트게늄",    "usage": "합성 원소"},
    "Cn": {"number": 112, "name": "코페르니슘",  "usage": "합성 원소"},
    "Nh": {"number": 113, "name": "니호늄",      "usage": "합성 원소"},
    "Fl": {"number": 114, "name": "플레로븀",    "usage": "합성 원소"},
    "Mc": {"number": 115, "name": "모스코븀",    "usage": "합성 원소"},
    "Lv": {"number": 116, "name": "리버모륨",    "usage": "합성 원소"},
    "Ts": {"number": 117, "name": "테네신",      "usage": "합성 원소"},
    "Og": {"number": 118, "name": "오가네손",    "usage": "합성 원소"},
}

st.title("118개 원소 정보")
st.write("원자번호와 원소 이름, 주요 쓰임새를 확인할 수 있습니다.")

for symbol, info in elements_info.items():
    st.subheader(f"{info['number']}. {info['name']} ({symbol})")
    st.write(f"**주요 쓰임새:** {info['usage']}")
